#!/usr/bin/env python3
"""Generate boot_logo_data.c from a 16-colour (4-bit) indexed PNG.

The logo is packed as 4-bit indexed pixels (2 px/byte, high nibble first) to
match the firmware's indexed-bitmap format (color_format == 16, index 0 =
transparent), then LZ4 *block* compressed (no frame header) so the firmware can
inflate it with a single LZ4_decompress_safe() call into a fixed-size buffer.

Usage:
    python gen_boot_logo.py <input.png> [-o <output.c>]

Requires: Pillow, lz4  (pip install pillow lz4)
"""
import argparse
import os
import sys

from PIL import Image
import lz4.block


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("png", help="16-colour indexed PNG (mode 'P')")
    ap.add_argument(
        "-o",
        "--output",
        default=os.path.join(os.path.dirname(__file__), "..", "src", "boot_logo_data.c"),
        help="output C file",
    )
    args = ap.parse_args()

    im = Image.open(args.png)
    if im.mode != "P":
        # Quantise to a 16-colour palette, reserving index 0 as transparent.
        im = im.convert("RGBA").quantize(colors=16, method=Image.MEDIANCUT)
    width, height = im.size
    if width % 2 != 0:
        print(f"error: width {width} must be even (2 px per byte)", file=sys.stderr)
        return 1

    palette = im.getpalette() or []
    palette = palette[: 16 * 3] + [0] * (16 * 3 - len(palette[: 16 * 3]))

    idx = list(im.getdata())
    if max(idx) > 15:
        print(f"error: pixel index {max(idx)} > 15 (not 4-bit)", file=sys.stderr)
        return 1

    # Pack 2 px/byte, high nibble = even pixel (matches firmware unpack).
    packed = bytearray()
    for i in range(0, len(idx), 2):
        hi = idx[i] & 0x0F
        lo = idx[i + 1] & 0x0F if i + 1 < len(idx) else 0
        packed.append((hi << 4) | lo)
    raw_size = len(packed)
    assert raw_size == width * height // 2, raw_size

    comp = lz4.block.compress(bytes(packed), mode="high_compression",
                              compression=12, store_size=False)

    def carr(data, per_line=16):
        out = []
        for i in range(0, len(data), per_line):
            out.append("\t" + ", ".join(f"0x{b:02x}" for b in data[i:i + per_line]) + ",")
        return "\n".join(out)

    pal_rows = "\n".join(
        f"\t{{0x{palette[i*3]:02x}, 0x{palette[i*3+1]:02x}, 0x{palette[i*3+2]:02x}}},"
        for i in range(16)
    )

    name = os.path.basename(args.png)
    c = f"""/* Auto-generated by modules/halo/tools/gen_boot_logo.py from {name}. Do not edit. */
#include <zephyr/kernel.h>
#include "halo/boot_logo.h"

#ifdef CONFIG_HALO_BOOT_LOGO

const uint16_t halo_boot_logo_width = {width};
const uint16_t halo_boot_logo_height = {height};

/* RGB palette, index 0 is transparent. */
const uint8_t halo_boot_logo_palette[16][3] = {{
{pal_rows}
}};

/* Decompressed size of the 4-bit packed indices (2 px/byte). */
const uint32_t halo_boot_logo_raw_size = {raw_size};

/* LZ4 block-compressed 4-bit indexed pixels. */
const uint8_t halo_boot_logo_lz4[] = {{
{carr(comp)}
}};
const uint32_t halo_boot_logo_lz4_size = sizeof(halo_boot_logo_lz4);

#endif /* CONFIG_HALO_BOOT_LOGO */
"""

    out = os.path.normpath(args.output)
    with open(out, "w") as f:
        f.write(c)

    ratio = 100.0 * len(comp) / raw_size
    print(f"{name}: {width}x{height}, 4-bit indices {raw_size} B -> "
          f"LZ4 {len(comp)} B ({ratio:.1f}%)")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
