#!/usr/bin/env python3
"""Rasterize a TTF at an exact pixel size into an Adafruit-GFX font header.

Unlike Adafruit's fontconvert (which sizes fonts in points at 141 DPI and so
cannot hit exact pixel sizes), this renders with FreeType's mono mode at a
pixel size given on the command line. That matters for pixel fonts such as
Dogica, which are only crisp at integer multiples of their 8px design size —
larger sizes come free at draw time via the canvas integer-scale parameter.

Usage:
    gen_gfx_font.py FONT.ttf PIXEL_SIZE --name Dogica8px -o Dogica8px.h

Requires Pillow (available in the workspace venv: ../../../../.venv).
"""

import argparse
import math
import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x7E  # printable ASCII, same range as the Adafruit fonts


def render_glyph(font, ch, px):
    """Render one glyph in mono (non-antialiased) mode.

    Returns (rows, width, height, x_offset, y_offset, x_advance) where rows is
    a list of per-row pixel booleans for the cropped ink bounding box and
    y_offset is relative to the baseline (negative = above), matching the
    GFXglyph convention.
    """
    ascent, _ = font.getmetrics()
    pad = px  # headroom so negative bearings don't clip
    img = Image.new("1", (px * 4, px * 4), 0)
    ImageDraw.Draw(img).text((pad, pad), ch, font=font, fill=1)
    bbox = img.getbbox()
    advance = round(font.getlength(ch))
    if bbox is None:  # space
        return [], 0, 0, 0, 0, advance
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    pixels = img.load()
    rows = [[bool(pixels[x, y]) for x in range(x0, x1)] for y in range(y0, y1)]
    # Ink was drawn with the layout box top at `pad`; the baseline sits
    # `ascent` below that.
    return rows, w, h, x0 - pad, (y0 - pad) - ascent, advance


def pack_bits(rows):
    """Pack row-major pixels MSB-first into bytes (GFX bitmap format)."""
    bits = [px for row in rows for px in row]
    out = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j, bit in enumerate(bits[i : i + 8]):
            if bit:
                byte |= 0x80 >> j
        out.append(byte)
    return bytes(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("ttf", help="path to the source TTF")
    ap.add_argument("px", type=int, help="exact pixel size to rasterize at")
    ap.add_argument("--name", required=True, help="C identifier, e.g. Dogica8px")
    ap.add_argument("-o", "--out", required=True, help="output header path")
    args = ap.parse_args()

    font = ImageFont.truetype(args.ttf, args.px)
    family, style = font.getname()
    ascent, descent = font.getmetrics()
    y_advance = ascent + abs(descent) + 2  # +2px leading, cosmetic only

    bitmaps = bytearray()
    glyphs = []
    for cp in range(FIRST, LAST + 1):
        rows, w, h, xo, yo, adv = render_glyph(font, chr(cp), args.px)
        glyphs.append((len(bitmaps), w, h, adv, xo, yo, cp))
        bitmaps += pack_bits(rows)

    name = args.name
    with open(args.out, "w") as f:
        f.write(
            f"// {family} {style} rasterized at {args.px}px "
            f"({len(glyphs)} glyphs, ASCII 0x{FIRST:02X}-0x{LAST:02X}).\n"
            f"// Generated by modules/canvas/tools/gen_gfx_font.py -- do not edit.\n"
            f"// Font (c) Roberto Mocci, SIL Open Font License 1.1 -- see license.txt.\n\n"
        )
        f.write(f"const uint8_t {name}Bitmaps[] PROGMEM = {{\n")
        for i in range(0, len(bitmaps), 12):
            chunk = ", ".join(f"0x{b:02X}" for b in bitmaps[i : i + 12])
            f.write(f"  {chunk},\n" if i + 12 < len(bitmaps) else f"  {chunk} }};\n")
        f.write(f"\nconst GFXglyph {name}Glyphs[] PROGMEM = {{\n")
        for i, (off, w, h, adv, xo, yo, cp) in enumerate(glyphs):
            end = "," if i < len(glyphs) - 1 else " };"
            label = chr(cp) if cp != 0x5C else "backslash"
            f.write(
                f"  {{ {off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d} }}{end}"
                f"   // 0x{cp:02X} '{label}'\n"
            )
        f.write(
            f"\nconst GFXfont {name} PROGMEM = {{\n"
            f"  (uint8_t  *){name}Bitmaps,\n"
            f"  (GFXglyph *){name}Glyphs,\n"
            f"  0x{FIRST:02X}, 0x{LAST:02X}, {y_advance} }};\n\n"
            f"// Approx. {len(bitmaps) + len(glyphs) * 12 + 16} bytes\n"
        )
    total = len(bitmaps) + len(glyphs) * 12 + 16
    print(f"{args.out}: {len(glyphs)} glyphs, {len(bitmaps)}B bitmaps, ~{total}B total")


if __name__ == "__main__":
    sys.exit(main())
