CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
CONFIG_COUNTER=y
CONFIG_COUNTER_RTC_SNPS_DW=y
CONFIG_COUNTER_SNPS_DW=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_BOOT_DELAY=3000
CONFIG_XIP=y
CONFIG_CORTEX_M_SYSTICK_IDLE_TIMER=n
CONFIG_POWEROFF=y

#BLE
CONFIG_BT=y
CONFIG_BT_CUSTOM=y

#Audio
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y
CONFIG_T5838=y
CONFIG_T5838_AAD_TRIGGER=y

CONFIG_SENSOR=y