CONFIG_MAX98357A_AUDIO=y
CONFIG_I2S=y
CONFIG_AUDIO=y
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_PRINTK=y

# Sync block tuning
CONFIG_MAX98357A_AUDIO_SYNC_BLOCK_SIZE=1024
CONFIG_MAX98357A_AUDIO_SYNC_BLOCK_COUNT=4